spring.application.name=payment-processor

server.servlet.context-path=/api/v1
server.port=8080

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs

spring.datasource.url=${POSTGRES_DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

ledger.engine.base-url={LEDGER_ENGINE_BASE_URL}
ledger.engine.api-key={LEDGER_ENGINE_API_KEY}
